#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# SnapForge - One-Command Builder
# Generated by NODAYSIDLE PRD Compiler
# Usage: cd <project-folder> && bash build.sh
# ============================================================

echo "======================================"
echo "  Building: SnapForge"
echo "======================================"
echo ""

# Collect all doc files into context
CONTEXT=""
LOADED=0
for doc in PRD.md ARD.md TRD.md TASKS.md AGENT.md DESIGN.md; do
  if [ -f "$doc" ]; then
    echo "[+] Loading $doc"
    CONTEXT="$CONTEXT
--- $doc ---
$(cat "$doc")
"
    LOADED=$((LOADED + 1))
  else
    echo "[ ] Skipping $doc (not found)"
  fi
done

if [ "$LOADED" -eq 0 ]; then
  echo ""
  echo "[!] No document files found. Nothing to build."
  exit 1
fi

echo ""
echo "Starting build with Claude ($LOADED docs loaded)..."
echo "--------------------------------------"
echo ""

# Write prompt to a temp file (avoids heredoc quoting issues on bash 3.2)
PROMPT_FILE="$(mktemp)"
cat > "$PROMPT_FILE" <<PROMPT_END
You are building a project called "SnapForge".

Here are all the project documents:

$CONTEXT

CRITICAL INSTRUCTIONS:
1. Read EVERY document above carefully before writing any code
2. Read CLAUDE.md in this directory for stack, rules, and design system
3. Create the full project scaffold (directories + files) based on ARD.md
4. Implement EVERY task from TASKS.md — do not stop after the first task
5. Follow ALL rules from AGENT.md for every decision
6. Match the design direction from DESIGN.md (colors, typography, mood)
7. Keep building until the ENTIRE project is complete and functional

Do NOT stop after creating one file. Build the COMPLETE working project.
PROMPT_END

# Run Claude in full agent mode (not --print) so it can create files
# CLAUDE.md in the current directory provides project context automatically
claude --dangerously-skip-permissions -p "$(cat "$PROMPT_FILE")"

rm -f "$PROMPT_FILE"

echo ""
echo "======================================"
echo "  Build complete!"
echo "======================================"
